version: "3.7"
services: 
    qrq-database:
        image: bitnami/postgresql:latest
        container_name: qrq-database-container
        ports: 
            - '5432:5432'
        environment: 
            - POSTGRESQL_USERNAME=qrqadmin
            - POSTGRESQL_PASSWORD=test123
            - POSTGRESQL_DATABASE=qrqDB
            - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
        volumes: 
            - ./postgresql:/bitnami/postgresql
        env_file: 
            - ./.env
        networks: 
            - main_bridge
networks :
    main_bridge:
        external:
            name : main_bridge