version: "3.7"
services: 
    qrq-api:
        image: qrq-image/base
        container_name: qrq-api-container
        ports: 
            - '3000:3000'
        environment: 
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USERNAME=${POSTGRES_USERNAME}
            - POSTGRES_PWD=${POSTGRES_PWD}
            - POSTGRES_DBNAME=${POSTGRES_DBNAME}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DIALECT=${POSTGRES_DIALECT}
        volumes: 
            - ./:/app
        env_file: 
            - ./.env
        networks: 
            - main_bridge
networks :
    main_bridge:
        external:
            name : main_bridge