version: "3.7"
services: 
    qrq-api:
        image: qrq-image/base
        container_name: qrq-api-container
        ports: 
            - '3000:3000'
        environment: 
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USERNAME=${POSTGRES_USERNAME}
            - POSTGRES_PWD=${POSTGRES_PWD}
            - POSTGRES_DBNAME=${POSTGRES_DBNAME}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DIALECT=${POSTGRES_DIALECT}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
        volumes: 
            - ./:/app
        env_file: 
            - ./.env
        networks: 
            - main_bridge
        links:
            - qrq-redis
    qrq-redis:
        image: redis
        container_name: qrq-redis-container
        volumes:
            - redis:/var/www/data/redis
        command: redis-server --appendonly yes
        networks:
            - main_bridge
        restart: unless-stopped
        ports:
            - "6379:6379"
networks :
    main_bridge:
        name : main_bridge
volumes:
    redis: