version: "3.7"
services: 
    qrq-api:
        build: .
        container_name: qrq-api-container
        ports: 
            - '3000:3000'
        environment: 
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
        volumes: 
            - ./:/app
        env_file: 
            - ./.env
        depends_on:
            - postgres
    
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
        ports: 
            - '5432:5432'
        volumes:
            - qrq-db:/var/lib/postgresql/data

volumes:
    qrq-db: